#include "app/CommandCatalog.hpp"

#include <array>

namespace pkmn::cli {
namespace {

constexpr std::array<CommandSpec, 108> kCommands{{
    {"General", "doctor", "pkmn doctor [--deep] [--format json]",
     "Check internal readiness; --deep runs a deterministic generation self-test."},
    {"General", "completion", "pkmn completion <bash|zsh|fish>",
     "Generate shell completion source."},
    {"General", "config show", "pkmn config show [--format text|json]",
     "Show compiled safety and default policy."},
    {"General", "get-all-cmds",
     "pkmn get-all-cmds [--format text|json|markdown] [--output <file>]",
     "Print the complete command catalog compiled into this executable."},
    {"General", "interactive", "pkmn interactive",
     "Open the beginner-oriented guided workflow for all four paired conversion routes."},

    {"Pokemon Red saves", "red summary",
     "pkmn red summary <save.sav> [--format text|json|markdown] [--output <file>]",
     "Create a readable trainer, progress, party, inventory, and storage summary."},
    {"Pokemon Red saves", "red inspect",
     "pkmn red inspect <save.sav> [--format json]",
     "Inspect save size and checksum integrity."},
    {"Pokemon Red saves", "red validate",
     "pkmn red validate <save.sav> [--format json]",
     "Validate all known Red checksums."},
    {"Pokemon Red saves", "red repair-checksums",
     "pkmn red repair-checksums <save.sav> [--output <copy.sav>] [--auto-suffix]",
     "Write a checksum-repaired copy without modifying the source."},
    {"Pokemon Red saves", "red decode",
     "pkmn red decode <save.sav> [--output <file.red.json>|-] [--include-physical-image|--no-physical-image] [--auto-suffix]",
     "Export deterministic canonical Red JSON."},
    {"Pokemon Red saves", "red events list",
     "pkmn red events list [--category <category>] [--format json]",
     "List verified named event flags."},
    {"Pokemon Red saves", "red events search",
     "pkmn red events search <query> [--format json]",
     "Search verified named event flags."},
    {"Pokemon Red saves", "red events show",
     "pkmn red events show <EVENT_NAME> [--format json]",
     "Show one verified event definition."},
    {"Pokemon Red saves", "red validate-batch",
     "pkmn red validate-batch <save.sav>... [--format json]",
     "Validate several saves in one command."},
    {"Pokemon Red saves", "red decode-batch",
     "pkmn red decode-batch <save.sav>... --output-dir <directory> [--no-physical-image]",
     "Decode several saves into a transactional output directory."},
    {"Pokemon Red saves", "red validate-post-emulator",
     "pkmn red validate-post-emulator <before.sav> <after.sav> [--output-dir <directory>]",
     "Analyze and classify an emulator round trip."},
    {"Pokemon Red to FireRed conversion", "red convert",
     "pkmn red convert <save.sav> [output.sav] [--auto-repair-checksum] [--write-repaired-source <copy.sav>] [--template <clean-fire-red.sav>] [--salt <value>] [--keep-intermediate] [--auto-suffix]",
     "Validate and convert a Pokemon Red save into an auditable FireRed save."},
    {"Pokemon Red editing", "red edit", "pkmn red edit <save.sav>",
     "Open the interactive copy-first editor."},
    {"Pokemon Red editing", "red begin-edit",
     "pkmn red begin-edit <save.sav> [--output <session.json>]",
     "Start a scriptable semantic edit session."},
    {"Pokemon Red editing", "red edit-session",
     "pkmn red edit-session <session.json> <edits...> [--dry-run] [--format json] [--explain-error]",
     "Stage and validate one or more edits."},
    {"Pokemon Red editing", "red pokemon",
     "pkmn red pokemon <session.json> <party|species|nickname> <value> <rename|level|move> ... [--dry-run]",
     "Apply coherent party-Pokemon name, level/stat, or move/PP edits."},
    {"Pokemon Red editing", "red bag",
     "pkmn red bag <session.json> <add <item> <quantity>|remove <item>> [--dry-run]",
     "Add, merge, or remove bag stacks with synchronized slots and counts."},
    {"Pokemon Red editing", "red progress",
     "pkmn red progress <session.json> fly-destinations all [--dry-run]",
     "Apply verified progress presets without arbitrary map-state mutation."},
    {"Pokemon Red editing", "red pending-edits",
     "pkmn red pending-edits <session.json> [--format json]",
     "Show staged edits."},
    {"Pokemon Red editing", "red undo-edit",
     "pkmn red undo-edit <session.json> [--count <number>]",
     "Undo the most recent staged edits."},
    {"Pokemon Red editing", "red edit-history",
     "pkmn red edit-history <session.json> [--format json]",
     "Show edit history and annotations."},
    {"Pokemon Red editing", "red annotate-edit",
     "pkmn red annotate-edit <session.json> <note>",
     "Attach a note to an edit session."},
    {"Pokemon Red editing", "red validate-edit",
     "pkmn red validate-edit <session.json>",
     "Run generation, checksum, re-decode, and semantic validation without writing a save."},
    {"Pokemon Red editing", "red end-edit",
     "pkmn red end-edit <session.json> [--output <save.sav>] [--auto-suffix] [--dry-run] [--format json]",
     "Publish a validated edited copy and reports."},

    {"Canonical Red JSON", "rjson inspect",
     "pkmn rjson inspect <file.red.json|-> [--format json]",
     "Inspect canonical Red JSON and archival-image status."},
    {"Canonical Red JSON", "rjson validate",
     "pkmn rjson validate <file.red.json|-> [--format json] [--profile standard|strict|generation|archival]",
     "Validate schema, semantics, and optional physical image."},
    {"Canonical Red JSON", "rjson generate",
     "pkmn rjson generate <file.red.json|-> [output.sav|-] [--auto-suffix]",
     "Generate a deterministic save from semantic fields only."},
    {"Canonical Red JSON", "rjson reconstruct",
     "pkmn rjson reconstruct <file.red.json|-> [--output <save.sav>|-] [--auto-suffix]",
     "Reconstruct archived source bytes from physicalImage."},
    {"Canonical Red JSON", "rjson migrate",
     "pkmn rjson migrate <file.red.json> [--output <migrated.red.json>] [--auto-suffix]",
     "Apply compatible deterministic schema enrichment."},
    {"Canonical Red JSON", "rjson schema",
     "pkmn rjson schema [--format json]",
     "Describe the supported canonical schema contract."},
    {"Canonical Red JSON", "rjson generate-batch",
     "pkmn rjson generate-batch <file.red.json>... --output-dir <directory>",
     "Generate several semantic saves transactionally."},
    {"Pokemon Red to FireRed conversion", "rjson convert",
     "pkmn rjson convert <save.red.json> [output.sav] [--template <clean-fire-red.sav>] [--salt <value>] [--keep-intermediate] [--auto-suffix]",
     "Convert canonical Red JSON directly into an auditable FireRed save."},
    {"Pokemon Red to FireRed conversion", "rjson convert_to_frjson",
     "pkmn rjson convert_to_frjson <save.red.json> [output.fred.json] [--salt <value>] [--auto-suffix]",
     "Translate canonical Red semantics into a proposed FireRed JSON document."},
    {"Kanto remake conversion", "rjson convert_to_lgjson",
     "pkmn rjson convert_to_lgjson <save.red.json> [output.lg.json] [--salt <value>] [--auto-suffix]",
     "Translate canonical Red semantics into a proposed LeafGreen JSON document."},
    {"Canonical Red JSON", "rjson update_schema",
     "pkmn rjson update_schema <save.red.json> [--output <updated.red.json>] [--auto-suffix]",
     "Safely migrate Red JSON to the latest supported schema."},

    {"FireRed JSON", "frjson inspect",
     "pkmn frjson inspect <save.fred.json>",
     "Inspect native or planned FireRed JSON."},
    {"FireRed JSON", "frjson validate",
     "pkmn frjson validate <save.fred.json>",
     "Validate native or planned FireRed JSON."},
    {"FireRed JSON", "frjson schema",
     "pkmn frjson schema [--format json]",
     "Describe native and planned FireRed JSON contracts and release gates."},
    {"FireRed JSON", "frjson update_schema",
     "pkmn frjson update_schema <save.fred.json> [--output <updated.fred.json>] [--auto-suffix]",
     "Safely migrate FireRed JSON to the latest supported schema."},
    {"FireRed JSON", "frjson generate",
     "pkmn frjson generate <save.fred.json> [output.sav] [--template <clean-fire-red.sav>]",
     "Generate a template-backed FireRed save from accepted FireRed semantics."},
    {"FireRed JSON", "frjson reconstruct",
     "pkmn frjson reconstruct <save.fred.json> [--output <save.sav>]",
     "Reconstruct archived FireRed source bytes from physicalImage."},
    {"FireRed JSON", "frjson migrate",
     "pkmn frjson migrate <save.fred.json> [--output <migrated.fred.json>] [--auto-suffix]",
     "Apply compatible deterministic FireRed schema enrichment."},
    {"FireRed JSON", "frjson generate-batch",
     "pkmn frjson generate-batch <save.fred.json>... --output-dir <directory> [--template <clean.sav>]",
     "Generate several native or planned FireRed saves."},

    {"Pokemon FireRed saves", "fred summary",
     "pkmn fred summary <save.sav> [--detailed]",
     "Create a compact or detailed FireRed save summary."},
    {"Pokemon FireRed saves", "fred inspect",
     "pkmn fred inspect <save.sav> [--format json]",
     "Inspect FireRed slots, counters, sectors, and checksum state."},
    {"Pokemon FireRed saves", "fred validate",
     "pkmn fred validate <save.sav> [--format json]",
     "Validate FireRed sectors, active slot, and checksums."},
    {"Pokemon FireRed saves", "fred decode",
     "pkmn fred decode <save.sav> [--output <save.fred.json>]",
     "Export complete native FireRed schema 0.4.0 JSON."},
    {"Pokemon FireRed saves", "fred repair-checksums",
     "pkmn fred repair-checksums <save.sav> [--output <copy.sav>]",
     "Repair recognized FireRed main-section checksums in a new copy."},
    {"Pokemon FireRed saves", "fred validate-batch",
     "pkmn fred validate-batch <save.sav>... [--format json]",
     "Validate several FireRed saves."},
    {"Pokemon FireRed saves", "fred decode-batch",
     "pkmn fred decode-batch <save.sav>... --output-dir <directory>",
     "Decode several FireRed saves transactionally."},
    {"Pokemon FireRed saves", "fred validate-post-emulator",
     "pkmn fred validate-post-emulator <before.sav> <after.sav> [--output-dir <directory>]",
     "Validate a FireRed emulator save/close/reload round trip."},
    {"Pokemon FireRed editing", "fred edit",
     "pkmn fred edit <save.sav> [--output <copy.sav>] [safe edits]",
     "Apply narrow validated copy-first FireRed edits."},
    {"Pokemon FireRed editing", "fred begin-edit",
     "pkmn fred begin-edit <save.sav> [--output <session.json>]",
     "Start a safe FireRed edit session."},
    {"Pokemon FireRed editing", "fred edit-session",
     "pkmn fred edit-session <session.json> [safe edit options]",
     "Stage player, rival, money, coins, or badge edits."},
    {"Pokemon FireRed editing", "fred pokemon",
     "pkmn fred pokemon <session.json> party <slot> rename <name>",
     "Stage a safe party-Pokemon nickname edit."},
    {"Pokemon FireRed editing", "fred bag",
     "pkmn fred bag <session.json> quantity <pocket> <slot> <item-id> <quantity>",
     "Change an existing verified item stack quantity."},
    {"Pokemon FireRed editing", "fred progress",
     "pkmn fred progress <session.json> badge <1-8> <on|off>",
     "Stage the compact badge progress edit supported by Save Genie."},
    {"Pokemon FireRed editing", "fred pending-edits",
     "pkmn fred pending-edits <session.json>", "Show staged FireRed edits."},
    {"Pokemon FireRed editing", "fred undo-edit",
     "pkmn fred undo-edit <session.json> [--count <number>]", "Undo staged FireRed edits."},
    {"Pokemon FireRed editing", "fred edit-history",
     "pkmn fred edit-history <session.json>", "Show FireRed edit history."},
    {"Pokemon FireRed editing", "fred annotate-edit",
     "pkmn fred annotate-edit <session.json> <note>", "Annotate a FireRed edit session."},
    {"Pokemon FireRed editing", "fred validate-edit",
     "pkmn fred validate-edit <session.json>", "Validate staged edits without publishing a save."},
    {"Pokemon FireRed editing", "fred end-edit",
     "pkmn fred end-edit <session.json> [--output <copy.sav>]", "Publish a validated edited FireRed copy."},
    {"Pokemon FireRed saves", "fred events list",
     "pkmn fred events list [--kind flag|variable] [--format json]",
     "List pinned pret FireRed flags or variables."},
    {"Pokemon FireRed saves", "fred events search",
     "pkmn fred events search <query> [--kind flag|variable] [--format json]",
     "Search pinned pret FireRed flags or variables."},
    {"Pokemon FireRed saves", "fred events show",
     "pkmn fred events show <name|id> [--kind flag|variable] [--format json]",
     "Show one pinned pret FireRed flag or variable."},

    {"Pokemon Red to FireRed conversion", "convert red-firered",
     "pkmn convert red-firered <red.sav|red.json> [output.sav] [conversion options]",
     "Convert either supported Red source form to FireRed."},
    {"Kanto remake conversion", "convert red-leafgreen",
     "pkmn convert red-leafgreen <red.sav|red.json> [output.sav] [conversion options]",
     "Convert a declared Pokemon Red source to LeafGreen (static/community-test evidence)."},
    {"Kanto remake conversion", "convert blue-firered",
     "pkmn convert blue-firered <blue.sav|blue.json> [output.sav] [conversion options]",
     "Convert a declared Pokemon Blue source to FireRed (static/community-test evidence)."},
    {"Kanto remake conversion", "convert blue-leafgreen",
     "pkmn convert blue-leafgreen <blue.sav|blue.json> [output.sav] [conversion options]",
     "Convert a declared Pokemon Blue source to LeafGreen (static/community-test evidence)."},
    {"Pokemon Blue saves", "blue decode",
     "pkmn blue decode <save.sav> [--output <save.blue.json>]",
     "Decode through the shared Gen I engine with an explicit GEN1_BLUE profile."},
    {"Pokemon Blue saves", "blue convert",
     "pkmn blue convert <save.sav> [output.sav]",
     "Convenience alias for the paired Blue-to-LeafGreen route."},
    {"Pokemon Blue JSON", "bjson convert",
     "pkmn bjson convert <save.blue.json> [output.sav]",
     "Convert canonical Blue JSON to LeafGreen."},
    {"Pokemon Blue JSON", "bjson convert_to_lgjson",
     "pkmn bjson convert_to_lgjson <save.blue.json> [output.lg.json]",
     "Plan Blue-to-LeafGreen conversion without writing a save."},
    {"Pokemon Blue JSON", "bjson convert_to_frjson",
     "pkmn bjson convert_to_frjson <save.blue.json> [output.fred.json]",
     "Plan Blue-to-FireRed conversion without writing a save."},
    {"Pokemon LeafGreen saves", "leafgreen decode",
     "pkmn leafgreen decode <save.sav> [--output <save.lg.json>]",
     "Decode through the shared Kanto-remake engine with GEN3_LEAFGREEN profile."},
    {"Pokemon LeafGreen saves", "leafgreen validate",
     "pkmn leafgreen validate <save.sav> [--format json]",
     "Validate the shared Gen III Kanto-remake save container."},
    {"Pokemon LeafGreen JSON", "lgjson generate",
     "pkmn lgjson generate <save.lg.json> [output.sav] [--template <clean.sav>]",
     "Generate a LeafGreen-profile save through the shared remake engine."},
    {"Pokemon LeafGreen JSON", "lgjson validate",
     "pkmn lgjson validate <save.lg.json>",
     "Validate native or planned LeafGreen-profile JSON."},
    {"Pokemon Red to FireRed conversion", "convert routes",
     "pkmn convert routes [--format json]",
     "List typed game profiles, conversion capabilities, and evidence labels."},
    {"Pokemon Red to FireRed conversion", "convert inspect",
     "pkmn convert inspect <event|trainer|item> [query]",
     "Inspect pinned bridge authority records."},
    {"Pokemon Red to FireRed conversion", "convert explain",
     "pkmn convert explain <event|trainer|item> <query>",
     "Explain a bridge decision with source evidence."},
    {"Pokemon Red to FireRed conversion", "convert validate-manifest",
     "pkmn convert validate-manifest <conversion-manifest.json>",
     "Validate an auditable conversion manifest."},
    {"Pokemon Red to FireRed conversion", "convert batch",
     "pkmn convert batch <source.sav|source.json>... --route <route> --output-dir <directory> [--template <clean.sav>]",
     "Convert several declared sources through one selected available route."},
    {"Proof workflows", "proof convert",
     "pkmn proof convert <route> <source.json> [--output-dir <directory>]",
     "Create a deterministic static proof package for any available conversion route."},

    {"Comparison", "compare progress",
     "pkmn compare progress <older.sav> <newer.sav> [report options]",
     "Explain gameplay progress between two backups from the same playthrough."},
    {"Comparison", "compare physical",
     "pkmn compare physical <a.sav> <b.sav> [report options]",
     "Compare physical bytes, ranges, percentages, and hashes."},
    {"Comparison", "compare semantic",
     "pkmn compare semantic <a.red.json> <b.red.json> [report options]",
     "Compare canonical semantic fields."},
    {"Comparison", "compare semantic-batch",
     "pkmn compare semantic-batch <baseline.red.json> <candidate.red.json>... [--format json]",
     "Compare several canonical documents to one baseline."},
    {"Comparison", "compare firered-semantic",
     "pkmn compare firered-semantic <a.fred.json> <b.fred.json> [--output-json <file>]",
     "Compare FireRed semantics while excluding archival physical bytes."},
    {"Comparison", "compare firered-progress",
     "pkmn compare firered-progress <older.sav> <newer.sav> [--output-json <file>]",
     "Decode and compare two FireRed progress saves."},
    {"Comparison", "compare firered-pokemon",
     "pkmn compare firered-pokemon <a.fred.json> <b.fred.json>", "Compare party, PC, and daycare data."},
    {"Comparison", "compare firered-events",
     "pkmn compare firered-events <a.fred.json> <b.fred.json>", "Compare event and variable state."},
    {"Comparison", "compare firered-trainers",
     "pkmn compare firered-trainers <a.fred.json> <b.fred.json>", "Compare trainer-defeat state."},
    {"Comparison", "compare firered-items",
     "pkmn compare firered-items <a.fred.json> <b.fred.json>", "Compare inventory and obtained-history state."},
    {"Comparison", "compare firered-fly",
     "pkmn compare firered-fly <a.fred.json> <b.fred.json>", "Compare Fly destinations."},
    {"Comparison", "compare firered-hall-of-fame",
     "pkmn compare firered-hall-of-fame <a.fred.json> <b.fred.json>", "Compare Hall of Fame data."},
    {"Comparison", "compare bridge",
     "pkmn compare bridge <red.json> <fred.json> [--manifest <file>]",
     "Audit Red source, proposed FireRed target, and optional manifest."},

    {"Proof", "proof red",
     "pkmn proof red <source.sav> [--output-dir <directory>] [--zip|--zip-output <archive.zip>] [--auto-suffix]",
     "Run decode, generation, comparison, determinism, and isolation proofs."},
    {"Proof", "proof post-emulator",
     "pkmn proof post-emulator --before <save.sav> --after <save.sav> [--output-dir <directory>|--proof-dir <directory>]",
     "Continue a proof package after manual emulator testing."},
    {"Proof", "proof verify",
     "pkmn proof verify <proof-directory|proof.zip> [--format json]",
     "Verify proof hashes, schemas, ZIP safety, and generated checksums."},
    {"Proof", "proof fred",
     "pkmn proof fred <complete.fred.json> [--template <clean.sav>] [--output-dir <directory>]",
     "Run the automated Phase 5 native FireRed generation proof."},
    {"Proof", "proof red-to-firered",
     "pkmn proof red-to-firered <save.red.json> [--template <clean.sav>] [--output-dir <directory>]",
     "Run the automated Phase 6 conversion proof and prepare MAQ verification."},
}};

} // namespace

std::span<const CommandSpec> AvailableCommands() { return kCommands; }

} // namespace pkmn::cli
