#include "app/CommandCatalog.hpp"

#include <array>

namespace pkmn::cli {
namespace {

constexpr std::array<CommandSpec, 41> kCommands{{
    {"General", "doctor", "pkmn doctor [--deep] [--format json]",
     "Check internal readiness; --deep runs a deterministic generation self-test."},
    {"General", "completion", "pkmn completion <bash|zsh|fish>",
     "Generate shell completion source."},
    {"General", "config show", "pkmn config show [--format text|json]",
     "Show compiled safety and default policy."},
    {"General", "get-all-cmds",
     "pkmn get-all-cmds [--format text|json|markdown] [--output <file>]",
     "Print the complete command catalog compiled into this executable."},

    {"Pokemon Red saves", "red summary",
     "pkmn red summary <save.sav> [--format text|json|markdown] [--output <file>]",
     "Create a readable trainer, progress, party, inventory, and storage summary."},
    {"Pokemon Red saves", "red inspect",
     "pkmn red inspect <save.sav> [--format json]",
     "Inspect save size and checksum integrity."},
    {"Pokemon Red saves", "red validate",
     "pkmn red validate <save.sav> [--format json]",
     "Validate all known Red checksums."},
    {"Pokemon Red saves", "red repair-checksums",
     "pkmn red repair-checksums <save.sav> [--output <copy.sav>] [--auto-suffix]",
     "Write a checksum-repaired copy without modifying the source."},
    {"Pokemon Red saves", "red decode",
     "pkmn red decode <save.sav> [--output <file.red.json>|-] [--include-physical-image|--no-physical-image] [--auto-suffix]",
     "Export deterministic canonical Red JSON."},
    {"Pokemon Red saves", "red events list",
     "pkmn red events list [--category <category>] [--format json]",
     "List verified named event flags."},
    {"Pokemon Red saves", "red events search",
     "pkmn red events search <query> [--format json]",
     "Search verified named event flags."},
    {"Pokemon Red saves", "red events show",
     "pkmn red events show <EVENT_NAME> [--format json]",
     "Show one verified event definition."},
    {"Pokemon Red saves", "red validate-batch",
     "pkmn red validate-batch <save.sav>... [--format json]",
     "Validate several saves in one command."},
    {"Pokemon Red saves", "red decode-batch",
     "pkmn red decode-batch <save.sav>... --output-dir <directory> [--no-physical-image]",
     "Decode several saves into a transactional output directory."},
    {"Pokemon Red saves", "red validate-post-emulator",
     "pkmn red validate-post-emulator <before.sav> <after.sav> [--output-dir <directory>]",
     "Analyze and classify an emulator round trip."},
    {"Pokemon Red editing", "red edit", "pkmn red edit <save.sav>",
     "Open the interactive copy-first editor."},
    {"Pokemon Red editing", "red begin-edit",
     "pkmn red begin-edit <save.sav> [--output <session.json>]",
     "Start a scriptable semantic edit session."},
    {"Pokemon Red editing", "red edit-session",
     "pkmn red edit-session <session.json> <edits...> [--dry-run] [--format json] [--explain-error]",
     "Stage and validate one or more edits."},
    {"Pokemon Red editing", "red pokemon",
     "pkmn red pokemon <session.json> <party|species|nickname> <value> <rename|level|move> ... [--dry-run]",
     "Apply coherent party-Pokemon name, level/stat, or move/PP edits."},
    {"Pokemon Red editing", "red bag",
     "pkmn red bag <session.json> <add <item> <quantity>|remove <item>> [--dry-run]",
     "Add, merge, or remove bag stacks with synchronized slots and counts."},
    {"Pokemon Red editing", "red progress",
     "pkmn red progress <session.json> fly-destinations all [--dry-run]",
     "Apply verified progress presets without arbitrary map-state mutation."},
    {"Pokemon Red editing", "red pending-edits",
     "pkmn red pending-edits <session.json> [--format json]",
     "Show staged edits."},
    {"Pokemon Red editing", "red undo-edit",
     "pkmn red undo-edit <session.json> [--count <number>]",
     "Undo the most recent staged edits."},
    {"Pokemon Red editing", "red edit-history",
     "pkmn red edit-history <session.json> [--format json]",
     "Show edit history and annotations."},
    {"Pokemon Red editing", "red annotate-edit",
     "pkmn red annotate-edit <session.json> <note>",
     "Attach a note to an edit session."},
    {"Pokemon Red editing", "red validate-edit",
     "pkmn red validate-edit <session.json>",
     "Run generation, checksum, re-decode, and semantic validation without writing a save."},
    {"Pokemon Red editing", "red end-edit",
     "pkmn red end-edit <session.json> [--output <save.sav>] [--auto-suffix] [--dry-run] [--format json]",
     "Publish a validated edited copy and reports."},

    {"Canonical Red JSON", "rjson inspect",
     "pkmn rjson inspect <file.red.json|-> [--format json]",
     "Inspect canonical Red JSON and archival-image status."},
    {"Canonical Red JSON", "rjson validate",
     "pkmn rjson validate <file.red.json|-> [--format json] [--profile standard|strict|generation|archival]",
     "Validate schema, semantics, and optional physical image."},
    {"Canonical Red JSON", "rjson generate",
     "pkmn rjson generate <file.red.json|-> [output.sav|-] [--auto-suffix]",
     "Generate a deterministic save from semantic fields only."},
    {"Canonical Red JSON", "rjson reconstruct",
     "pkmn rjson reconstruct <file.red.json|-> [--output <save.sav>|-] [--auto-suffix]",
     "Reconstruct archived source bytes from physicalImage."},
    {"Canonical Red JSON", "rjson migrate",
     "pkmn rjson migrate <file.red.json> [--output <migrated.red.json>] [--auto-suffix]",
     "Apply compatible deterministic schema enrichment."},
    {"Canonical Red JSON", "rjson schema",
     "pkmn rjson schema [--format json]",
     "Describe the supported canonical schema contract."},
    {"Canonical Red JSON", "rjson generate-batch",
     "pkmn rjson generate-batch <file.red.json>... --output-dir <directory>",
     "Generate several semantic saves transactionally."},

    {"Comparison", "compare progress",
     "pkmn compare progress <older.sav> <newer.sav> [report options]",
     "Explain gameplay progress between two backups from the same playthrough."},
    {"Comparison", "compare physical",
     "pkmn compare physical <a.sav> <b.sav> [report options]",
     "Compare physical bytes, ranges, percentages, and hashes."},
    {"Comparison", "compare semantic",
     "pkmn compare semantic <a.red.json> <b.red.json> [report options]",
     "Compare canonical semantic fields."},
    {"Comparison", "compare semantic-batch",
     "pkmn compare semantic-batch <baseline.red.json> <candidate.red.json>... [--format json]",
     "Compare several canonical documents to one baseline."},

    {"Proof", "proof red",
     "pkmn proof red <source.sav> [--output-dir <directory>] [--zip|--zip-output <archive.zip>] [--auto-suffix]",
     "Run decode, generation, comparison, determinism, and isolation proofs."},
    {"Proof", "proof post-emulator",
     "pkmn proof post-emulator --before <save.sav> --after <save.sav> [--output-dir <directory>|--proof-dir <directory>]",
     "Continue a proof package after manual emulator testing."},
    {"Proof", "proof verify",
     "pkmn proof verify <proof-directory|proof.zip> [--format json]",
     "Verify proof hashes, schemas, ZIP safety, and generated checksums."},
}};

} // namespace

std::span<const CommandSpec> AvailableCommands() { return kCommands; }

} // namespace pkmn::cli
